import express from 'express';
import authRouter from './auth.routes.js';
import listRouter from './list.routes.js';
import libraryEntryRouter from './library-entry.routes.js';
import userRouter from './user.routes.js';
import collectionRouter from './collection.routes.js';
import catalogRouter from './catalog.routes.js';
import calendarRouter from './calendar.routes.js';
import notificationRouter from './notification.routes.js';
import socialRouter from './social.routes.js';

const router = express.Router();
router.use('/auth', authRouter);
router.use('/user', userRouter);
router.use('/list', listRouter);
router.use('/library/entries', libraryEntryRouter);
router.use('/collections', collectionRouter);
router.use('/catalog', catalogRouter);
router.use('/calendar', calendarRouter);
router.use('/notifications', notificationRouter);
router.use('/social', socialRouter);
export default router;
